[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.15"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/tokencard/ethertest"
  version = "v0.1.2"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[prune]
  go-tests = true
