[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.15"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/tokencard/assets"
  version = "0.9.0"

[[constraint]]
  name = "github.com/tokencard/ethertest"
  version = "v0.1.2"

[prune]
  go-tests = true
