---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oraclize-bridge-config
data:
  instance.json: |
    {
      "context_name": "eth_5564FED5CE",
      "latest_block_number": 287538,
      "oar": "0x2807ed83B0bCA2824CeE114844935B44C9EF8f2c",
      "node": {
          "main": "http://parity-poa:8545",
          "backup": []
      },
      "contracts": {
          "connector": {
              "binary": "/ethereum-bridge/contracts/binary/oraclizeConnector.binary",
              "abi": "/ethereum-bridge/contracts/abi/oraclizeConnector.json",
              "source": "/ethereum-bridge/contracts/ethereum-api/connectors/oraclizeConnector.sol"
          },
          "oar": {
              "binary": "/ethereum-bridge/contracts/binary/addressResolver.binary",
              "abi": "/ethereum-bridge/contracts/abi/addressResolver.json",
              "source": "/ethereum-bridge/contracts/ethereum-api/connectors/addressResolver.sol"
          }
      },
      "deterministic_oar": false,
      "deploy_gas": 3700000,
      "account": "0xc9c700007016cc407c40c2a04a43866ba4647a5f",
      "mode": "broadcast",
      "key_file": "/ethereum-bridge/config/instance/keys.json",
      "gas_price": 20000000000,
      "onchain_config": {
          "pricing": [
              {
                  "name": "IPFS",
                  "proof": 0,
                  "units": 10
              },
              {
                  "name": "IPFS",
                  "proof": 1,
                  "units": 10
              },
              {
                  "name": "swarm",
                  "proof": 0,
                  "units": 10
              },
              {
                  "name": "swarm",
                  "proof": 1,
                  "units": 10
              },
              {
                  "name": "URL",
                  "proof": 0,
                  "units": 10
              },
              {
                  "name": "URL",
                  "proof": 1,
                  "units": 10
              },
              {
                  "name": "URL",
                  "proof": 16,
                  "units": 50
              },
              {
                  "name": "URL",
                  "proof": 17,
                  "units": 50
              },
              {
                  "name": "URL",
                  "proof": 32,
                  "units": 50
              },
              {
                  "name": "URL",
                  "proof": 33,
                  "units": 50
              },
              {
                  "name": "Blockchain",
                  "proof": 0,
                  "units": 10
              },
              {
                  "name": "Blockchain",
                  "proof": 1,
                  "units": 10
              },
              {
                  "name": "nested",
                  "proof": 0,
                  "units": 10
              },
              {
                  "name": "nested",
                  "proof": 1,
                  "units": 10
              },
              {
                  "name": "nested",
                  "proof": 16,
                  "units": 50
              },
              {
                  "name": "nested",
                  "proof": 17,
                  "units": 50
              },
              {
                  "name": "nested",
                  "proof": 32,
                  "units": 50
              },
              {
                  "name": "nested",
                  "proof": 33,
                  "units": 50
              },
              {
                  "name": "WolframAlpha",
                  "proof": 0,
                  "units": 30
              },
              {
                  "name": "WolframAlpha",
                  "proof": 1,
                  "units": 30
              },
              {
                  "name": "computation",
                  "proof": 0,
                  "units": 500
              },
              {
                  "name": "computation",
                  "proof": 1,
                  "units": 500
              },
              {
                  "name": "computation",
                  "proof": 16,
                  "units": 540
              },
              {
                  "name": "computation",
                  "proof": 17,
                  "units": 540
              },
              {
                  "name": "computation",
                  "proof": 32,
                  "units": 540
              },
              {
                  "name": "computation",
                  "proof": 33,
                  "units": 540
              },
              {
                  "name": "random",
                  "proof": 0,
                  "units": 50
              },
              {
                  "name": "random",
                  "proof": 1,
                  "units": 50
              },
              {
                  "name": "random",
                  "proof": 48,
                  "units": 50
              },
              {
                  "name": "random",
                  "proof": 49,
                  "units": 50
              }
          ],
          "base_price": 0.00000277
      },
      "connector": "0xe64d89823fc170e301c71635bae154030657796a"
    }
