---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraclize-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oraclize-bridge
  template:
    metadata:
      labels:
        name: oraclize-bridge
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
        - name: oraclize-bridge
          imagePullPolicy: Always
          image: quay.io/token/oraclize-bridge:v1.0.0
          args:
            - "--instance=instance.json"
          volumeMounts:
            - name: keys
              mountPath: /ethereum-bridge/config/instance/keys.json
              subPath: keys.json
              readOnly: true
            - name: config
              mountPath: /ethereum-bridge/config/instance/instance.json
              subPath: instance.json
              readOnly: false
      volumes:
        - name: keys
          secret:
            secretName: oraclize-bridge-keys
            items:
              - key: keys.json
                path: keys.json
        - name: config
          configMap:
            name: oraclize-bridge-config
            items:
              - key: instance.json
                path: instance.json
