version: 2
jobs:
  vendor_and_test:
    docker:
      - image: quay.io/token/go-build:v0.2.2
    working_directory: /home/circleci/go/src/github.com/tokencard/contracts
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run: GOPATH=/home/circleci/go dep ensure -vendor-only
      - run: GOPATH=/home/circleci/go go test -v ./test/...
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"

  build_test:
    machine: true
    working_directory: /home/circleci/go/src/github.com/tokencard/contracts
    steps:
      - checkout
      - run: id
      - run: ls -la /
      - run: pwd
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run: ./build.sh
      - run: '[[ -z $(git status -uno --porcelain) ]] || (git status ; echo "Please run ./build.sh before commiting changes!"; exit 1)'

  mythril:
    docker:
      - image: quay.io/token/mythril:2018-07-05
    working_directory: /src
    steps:
      - checkout
      - run: myth -x *.sol

  snyk_check:
    docker:
      - image: quay.io/token/go-build:v0.2.2
    working_directory: /go/src/github.com/tokencard/contracts
    steps:
      - checkout
      - run: |
          apk add -U --no-cache git nodejs nodejs-npm
          go get -u github.com/golang/dep/cmd/dep
          dep ensure
          npm install -g snyk
          snyk auth ${SNYK_TOKEN}
          snyk test --org=token


workflows:
  version: 2
  build_deploy:
    jobs:
      - vendor_and_test
      - build_test:
          requires:
            - vendor_and_test
          filters:
            tags:
              ignore: ""
      - mythril:
          filters:
            tags:
              ignore: ""
      - snyk_check:
          context: snyk
