version: 2
jobs:
  build_test:
    docker:
      - image: node:9.0.0
    working_directory: /go/src/github.com/tokencard/bis
    steps:
      - checkout
      - run: npm install && npm test

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_test:
          filters:
            tags:
              ignore: ""
