version: 2
jobs:
  vendor_and_test:
    docker:
      - image: quay.io/token/go-build:v0.2.2
    working_directory: /home/circleci/go/src/github.com/tokencard/contracts
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendorx-{{ checksum "Gopkg.lock" }}
      - run: GOPATH=/home/circleci/go dep ensure
      - run: GOPATH=/home/circleci/go go test -v ./test/...
      - save_cache:
          key: vendorx-{{ checksum "Gopkg.lock" }}
          paths:
            - "vendor"

  build_test:
    machine: true
    working_directory: /home/circleci/go/src/github.com/tokencard/contracts
    steps:
      - checkout
      - run: id
      - run: ls -la /
      - run: pwd
      - restore_cache:
          keys:
            - vendorx-{{ checksum "Gopkg.lock" }}
      - run: ./build.sh
      - run: '[[ -z $(git status -uno --porcelain) ]] || (git status ; echo "Please run ./build.sh before commiting changes!"; exit 1)'

  mythril:
    docker:
      - image: quay.io/token/mythril:2018-07-05
    working_directory: /src
    steps:
      - checkout
      - run: myth -x *.sol

workflows:
  version: 2
  build_deploy:
    jobs:
      - vendor_and_test
      - build_test:
          requires:
            - vendor_and_test
          filters:
            tags:
              ignore: ""
      - mythril:
          filters:
            tags:
              ignore: ""
